[gcp_service_account]
type = "service_account"
project_id = "quanlyvattuapp-466901"
private_key_id = "..."
private_key = """-----BEGIN PRIVATE KEY-----
... (nội dung key của bạn)
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@quanlyvattuapp-466901.iam.gserviceaccount.com"
client_id = "101181194750464730636"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40quanlyvattuapp-466901.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
